name: API Automation Test Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20

      - name: Instalar Dependências
        run: npm ci

      - name: Iniciar ServeRest em background
        # Usamos nohup e & para rodar o servidor em segundo plano e continuar o pipeline
        run: nohup npx serverest start --port 3000 > serverest.log 2>&1 &

      - name: Aguardar servidor subir
        run: sleep 5 # Pequena pausa para garantir que o servidor iniciou

      - name: Executar Testes
        run: npm run test:allure
        continue-on-error: true # Permite que o relatório seja gerado mesmo com falhas nos testes

      - name: Gerar Relatório Allure
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy para GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history